version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: admin
      POSTGRES_DB: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: admin
      POSTGRES_DB: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:
